### ISSUE TITLE
Audio only playback not working on videos with self-harm warnings

### ISSUE THREAD

**Issue by przemo20** [schdie/we_firefox_ytop_mv3#1]
_(Not sure whether this is a some limitation, and you need to get used to it, or there is a way to fix it)_

### Example steps to reproduce
1. Visit https://www.youtube.com/watch?v=nZHXSN6lEEw
2. Discard the warning by clicking on the “I understand (...)” button
3. If the audio only playback mode is not already activated, click on “headphones” button (the button that gets added by the extension) inside the video player. Otherwise, click on that button twice – first to disable it, and second time – to enable it once again.

### Technical information

Browser: Firefox 130.0.1 (64-bit)
Extension version: 26

**Comment by schdie** [comment]
Hi, thank you for the report. This is probably a bug since I don't remember testing the extension with a video that had that characteristic. I'll look into it. 

Do you have autoplay enabled?

**Comment by przemo20** [comment]
> Do you have autoplay enabled?

I'm listening to my YouTube Mix collection (so the URL looks like this: `https://www.youtube.com/watch?v=nZHXSN6lEEw&list=RDcQVT_wu5g3w&index=25`), so you can say that autoplay is enabled.

But even if I go directly to the video (by following the steps I mentioned above), I can still reproduce it.

**Comment by schdie** [comment]
For posterity, here's what's going on: age-restricted streams can't be retrieved with the current way the logic in the code is implemented but changing to a special user agent just like yt-dlp does works around that, the problem arises with the new retrieved streams that require a decrypted signature, dealing with signatures was already in the code but recently Google added something new called poToken, a proof of origin token that validates the request, this token has to be the same for the original POST request and then it has to be in the final stream URL delivered to the player.

I'm working on it but no ETA since I have little time right now, but this will be fixed.

**Comment by schdie** [comment]
This is fixed now, it had nothing to do with the poToken. I'll update the extension in AMO as soon as I finish doing so some  more testing. Fixed with 2dc10a75598c7631bc391adb9c00c4cccffa5719
